name: Build Linux OS untuk Laptop 2014

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Tombol manual jalankan build di web GitHub

jobs:
  build-os:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Buildroot Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev file rsync \
          bc wget cpio unzip graphviz python3 libssl-dev

    - name: Clone Buildroot
      run: |
        git clone https://github.com --depth=1 $HOME/buildroot

    - name: Setup Compiler Cache (ccache)
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.ccache
        key: ccache-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          ccache-${{ runner.os }}-

    - name: Configure Buildroot
      run: |
        cd $HOME/buildroot
        # Menggunakan template PC Generic 64-bit untuk laptop/komputer x86_64
        make pc_x86_64_bios_defconfig
        
        # Mengaktifkan CCACHE otomatis lewat script agar build berikutnya cepat
        echo "BR2_CCACHE=y" >> .config
        echo "BR2_CCACHE_DIR=\"${{ github.workspace }}/.ccache\"" >> .config

    - name: Compile Operating System
      run: |
        cd $HOME/buildroot
        make -j$(nproc)

    - name: Upload Bootable Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: laptop-2014-linux-os
        path: |
          ${{ home }}/buildroot/output/images/sdcard.img
          ${{ home }}/buildroot/output/images/bzImage
