name: Build x86_64 Linux Distro

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-slim
    timeout-minutes: 360 # biar gak 6 jam mati

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt install build-essential binutils rsync wget libncurses-dev libelf-dev libssl-dev

      - name: Download Buildroot 2025.02.3
        run: |
          wget https://buildroot.org/downloads/buildroot-2025.02.3.tar.gz
          tar -xf buildroot-2025.02.3.tar.gz
          mv buildroot-2025.02.3 buildroot # <-- KUNCI NYA INI

      - name: Custom Configuration
        run: |
          make x86_64_defconfig
          
      - name: Build Distribution
        working-directory: buildroot
        run: |
          make -j$(nproc) # pake semua core biar cepet

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux-images
          path: buildroot/output/images/
